Alventa/AlventaMVC/Controllers/Order_DetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AlventaDB.EF;
using AlventaDB.Models;
using AlventaDB.Repos;
using PagedList.Mvc;
using PagedList;
using System.Net.Mail;
using Microsoft.Office.Interop.Excel;
using System.Reflection;

namespace AlventaMVC.Controllers
{
    public class Order_DetailController : Controller
    {
        private readonly Order_DetailRepo repo = new Order_DetailRepo();

        public async Task<ActionResult> Index(int? page, string from, string to)
        {
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            IEnumerable<Order_Detail> order_Detail;

            if (from == null || to == null)
            {
                order_Detail = (await repo.GetAllAsync()).Take(50);
            }
            else
            {
                order_Detail = from od in await repo.GetAllAsync()
                               where od.Order.OrderDate >= Convert.ToDateTime(@from) &&
                                     od.Order.OrderDate <= Convert.ToDateTime(to)
                               select od;
            }

            if (order_Detail == null)
            {
                return HttpNotFound();
            }

            Application oXL;
            _Workbook oWB;
            _Worksheet oSheet;
            string path = Server.MapPath("~/Files/test.xls");

            try
            {
                oXL = new Application();
                oXL.Visible = false;

                oWB = oXL.Workbooks.Add("");
                oSheet = (_Worksheet)oWB.ActiveSheet;

                oSheet.Cells[1, 1] = "Номер заказа";
                oSheet.Cells[1, 2] = "Дата заказа";
                oSheet.Cells[1, 3] = "Артикул товара";
                oSheet.Cells[1, 4] = "Название товара";
                oSheet.Cells[1, 5] = "Количество реализованных единиц товара";
                oSheet.Cells[1, 6] = "Цена реализации за единицу продукции";
                oSheet.Cells[1, 7] = "Скидка,%";
                oSheet.Cells[1, 8] = "Итоговая цена";

                oSheet.get_Range("A1", "H1").Font.Bold = true;
                oSheet.get_Range("A1", "H1").VerticalAlignment = XlVAlign.xlVAlignCenter;
                oSheet.get_Range("A1", "H1").HorizontalAlignment = XlVAlign.xlVAlignCenter;

                int row = 2;

                foreach (var o in order_Detail)
                {
                    oSheet.Cells[row, 1] = o.OrderID;
                    oSheet.Cells[row, 2] = o.Order.OrderDate;
                    oSheet.Cells[row, 3] = o.ProductID;
                    oSheet.Cells[row, 4] = o.Product.ProductName;
                    oSheet.Cells[row, 5] = o.Quantity;
                    oSheet.Cells[row, 6] = o.UnitPrice;
                    oSheet.Cells[row, 7] = o.Discount;

                    oSheet.Cells[row, 8].Formula = o.Discount == 0 ? $"=E{row}*F{row}" : $"=(E{row}*F{row})-(E{row}*F{row}*G{row})";

                    row++;
                }

                if (System.IO.File.Exists(path))
                {
                    System.IO.File.Delete(path);
                }

                oXL.UserControl = false;
                oWB.SaveAs(path, XlFileFormat.xlWorkbookDefault, Type.Missing, Type.Missing, false, false, XlSaveAsAccessMode.xlNoChange, Type.Missing, Type.Missing, Type.Missing, Type.Missing, Type.Missing);

                oWB.Close();
            }
            catch (Exception)
            {
                throw;
            }

            return View(order_Detail.ToPagedList(pageNumber,pageSize));
        }

        [HttpPost]
        public ActionResult Send(string email)
        {
            string path = Server.MapPath("~/Files/test.xls");
            MailAddress from = new MailAddress("parantovlad@mail.ru");
            MailAddress to = new MailAddress(email);

            MailMessage m = new MailMessage(from, to);
            m.Subject = "Test";
            m.Body = "<h2>Письмо-тест работы smtp-клиента</h2>";
            m.IsBodyHtml = true;
            m.Attachments.Add(new Attachment(path));

            SmtpClient smtp = new SmtpClient("smtp.mail.ru", 587);
            smtp.Credentials = new NetworkCredential("parantovlad@mail.ru", "******");
            smtp.EnableSsl = true;
            smtp.Send(m);
            
            return PartialView();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repo.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Alventa/AlventaMVC/Views/Order_Detail/Index.cshtml
@model PagedList.IPagedList<AlventaDB.Models.Order_Detail>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Order";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Отчёт по продажам </h2>
<div>
    <div class="form-group float-left col-md-8">
        @using (Html.BeginForm("Index", "Order_Detail", FormMethod.Post))
        {
            <label class="col-form-label float-left" for="from">С</label>
            <input type="text" class="form-control float-left" id="from" name="from" />
            <label class="col-form-label float-left" for="to">по</label>
            <input type="text" class="form-control float-left" id="to" name="to" />
            <input type="submit" class="btn btn-primary float-left" value="Запрос" />
        }
    </div>
    <div class="form-group float-right col-md-4">
        @using (Ajax.BeginForm("Send", new AjaxOptions { UpdateTargetId = "results" }))
        {
            <input type="email" class="form-control float-left" aria-describedby="emailHelp" placeholder="Enter email" id="email" name="email" />
            <input type="submit" class="btn btn-primary float-left" id="send" value="Отправить на почту" />
        }
        <div id="results"></div>
    </div>
</div>

<table class="table table-striped table-hover table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayName("Номер заказа")
            </th>
            <th>
                @Html.DisplayName("Дата заказа")
            </th>
            <th>
                @Html.DisplayName("Артикул товара")
            </th>
            <th>
                @Html.DisplayName("Название товара")
            </th>
            <th>
                @Html.DisplayName("Количество реализованных единиц товара")
            </th>
            <th>
                @Html.DisplayName("Цена реализации за единицу продукции")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.OrderDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

Alventa/AlventaMVC/Views/Order_Detail/Send.cshtml
Отправлено

Alventa/AlventaMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Alventa</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Alventa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Order <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Alventa</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>